default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  password: postgres
  user: postgres
  host: localhost
  port: 5433

development:
  <<: *default
  database: locus_development

test:
  <<: *default
  database: locus_test

production:
  <<: *default
  database: locus_production
